GET   http://localhost:8080/salidas
Content-Type: application/json

{
  "nombres": "Juan Carlos",
  "apellidos": "Pérez Gutiérrez",
  "dni": "87654321",
  "email": "juan.carlos@example.com",
  "contraseña": "querico"
}